backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

site_url: https://www.kindpup.com
display_url: https://www.kindpup.com
logo_url: "https://www.kindpup.com/img/kindpuplogo-medium.png"

show_preview_links: true

collections:
  - name: 'sitewide'
    label: 'Sitewide'
    identifier_field: name
    format: 'json'
    folder: 'assets/content/sitewide'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Full Legal Name', name: 'legal_name', widget: 'string' }
      - { label: 'Logo', name: 'logo', widget: 'file', required: false }
      - { label: 'Address Line 1', name: 'address_line_1', widget: 'string', required: false }
      - { label: 'Address Line 2', name: 'address_line_2', widget: 'string', required: false }
      - { label: 'Address Line 3', name: 'address_line_3', widget: 'string', required: false }
      - { label: 'Phone Number', name: 'phone_number', widget: 'string', required: false }
      - { label: 'Email Address', name: 'email_address', widget: 'string', required: false }
      - label: "Creeper Bar"
        name: "creeper_bar"
        widget: "object"
        fields:
        - { label: "Shown", name: "shown", widget: "boolean", default: true, required: false }
        - { label: 'Text', name: 'text', widget: 'string', required: false }
        - { label: 'Link', name: 'link', widget: 'string', required: false }
      - label: "Sign Up Boxes"
        name: "sign_up"
        widget: "object"
        fields:
        - { label: 'Text', name: 'text', widget: 'markdown', required: false, buttons: ["bold", "italic", "link", "heading-two", "heading-three", "bulleted-list"] }
        - { label: 'Button Text', name: 'button_text', widget: 'string', required: false }
        - { label: 'Button Link', name: 'button_link', widget: 'string', required: false }
      - label: "Footer Details"
        name: "footer_details"
        widget: "object"
        fields:
        - { label: 'Footer Company Para', name: 'para', widget: 'text', required: false }
        - { label: 'Footer Copyright', name: 'copyright', widget: 'string', required: false }
      - label: "Social Media"
        name: "social_media"
        widget: "object"
        fields:
        - { label: 'Show Social Media', name: 'show_social', widget: 'boolean', required: false }
        - { label: 'Facebook Link', name: 'facebook_link', widget: 'string', required: false }
        - { label: 'Instagram Link', name: 'instagram_link', widget: 'string', required: false }
        - { label: 'Twitter Link', name: 'twitter_link', widget: 'string', required: false }
        - { label: 'GitHub Link', name: 'github_link', widget: 'string', required: false }
        - { label: 'Dribble Link', name: 'dribble_link', widget: 'string', required: false }
      - label: "Contact Form"
        name: "contact_form"
        widget: "object"
        fields:
        - name: 'items'
          label: 'Contact Form Item'
          widget: "list"
          fields:
          - {label: "Text", name: "text", widget: "string"}
          - {label: "Required", name: "required", widget: "boolean", default: false, required: false }
          - {label: "Short Name", name: "short_name", widget: "string", required: false}
          - {label: "Placeholder", name: "placeholder", widget: "string"}
          - {label: "Field Type", name: "type", widget: "string"}
        - {label: "Submit Button Text", name: "button_text", widget: "string"}
      - { label: 'Store Component Number', name: 'comp_code', widget: 'string' }
      - { label: 'Site Code', name: 'page_code', widget: 'text' }

  - name: 'pages'
    label: 'Pages'
    identifier_field: name
    format: 'json'
    folder: 'assets/content/pages'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Page Name', name: 'name', widget: 'string' }
      - label: "Hero Slides"
        name: "hero"
        widget: "object"
        fields:
        - name: 'slides'
          label: 'Slide'
          widget: "list"
          fields:
          - { label: 'Header', name: 'header', widget: 'string', required: false }
          - { label: 'Show Slide', name: 'status', widget: 'boolean', required: false }
          - { label: 'Para', name: 'para', widget: 'text', required: false }
          - { label: 'Button Text', name: 'button_text', widget: 'string', required: false }
          - { label: 'Button Link', name: 'button_link', widget: 'string', required: false }
          - { label: 'Button Color', name: 'button_color', widget: 'string', required: false }
          - { label: 'Background Image', name: 'background_image', widget: 'file', required: false }
          - { label: 'Video', name: 'video', widget: 'file', required: false }
          - { label: 'Sub Image', name: 'sub_image', widget: 'file', required: false }
      - label: "Hero Options"
        name: "hero_options"
        widget: "object"
        fields:
        - { label: 'Auto Play?', name: 'autoplay', widget: 'boolean', required: false }
        - { label: 'Time To Move', name: 'time_to_move', widget: 'number', required: false }
        - { label: 'Loop?', name: 'loop', widget: 'boolean', required: false }
      - label: "Page Sections"
        name: "sections"
        widget: "list"
        slug: '{{name}}'
        fields:
        - { label: 'Section Name', name: 'name', widget: 'string', required: true }
        - { label: 'Show Section', name: 'status', widget: 'boolean', required: false }
        - label: "Section Text"
          name: "section_text"
          widget: "list"
          fields:
          - { label: 'Text', name: 'text', widget: 'markdown', required: false, buttons: ["bold", "italic", "link", "heading-two", "heading-three", "bulleted-list", "numbered-list"] }
        - label: "Section Images"
          name: "section_images"
          widget: "list"
          fields:
            - { label: 'Image Name', name: 'name', widget: 'string', required: false }
            - { label: 'Image', name: 'image', widget: 'file', required: false }
      - { label: 'Meta Description', name: 'meta_description', widget: 'string' }


  - name: 'nav'
    label: 'Nav Items'
    identifier_field: title
    format: 'json'
    folder: 'assets/content/nav'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: "Shown", name: "shown", widget: "boolean", default: true, required: false }
      - label: "Sort Number"
        name: "sort"
        widget: "number"
        default: 1
        valueType: "int"
        min: 1
        max: 20
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Link', name: 'link', widget: 'string' }
      - { label: 'Para', name: 'para', widget: 'text', required: false }
      - { label: 'Icon', name: 'icon', widget: 'file', required: false }